language: node_js
node_js:
  - "0.10"

before_script:
  - sleep 1 # give  server time to start
  - npm install -g bower

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
